// Types for the "Honesty Pilot" agent set, backed by CSV/JSON files under
// public/data/honesty-pilot/ (generated by scripts/build_pilot_v1.py).
// Kept separate from the legacy AgentSet union in types/index.ts on purpose —
// see the plan for this rebuild for why.

export type PilotModule = "D" | "PT" | "EP" | "MO";
export type TraitStyle = "score" | "pct" | "adj" | "dsc";

export interface HonestyPilotAgent {
  agentId: number;
  demAge: number;
  demGender: string | null;
  demEthnicity: string | null;
  demEducation: string;
  demIncome: string | null;
  demOccupation: string;
  demIndustry: string;
  demPolitics: string | null;
  demReligion: string | null;
  demText: string;
  hxHh: number;
  hxEm: number;
  hxEx: number;
  hxAg: number;
  hxCo: number;
  hxOp: number;
  psmRisk: number;
  psmPatience: number;
  psmAltruism: number;
  psmPosRec: number;
  psmNegRec: number;
  psmTrust: number;
  csDeontology: number;
  csUtilitarianism: number;
  humanRoll: number;
  humanReport: number;
  humanReason: string;
  humanHonest: boolean;
}

export interface HonestyPilotResult {
  experimentId: string;
  agentId: number;
  runId: number;
  agentReport: number;
  agentReason: string;
}

export interface HonestyPilotStatsResult {
  agentId: number;
  experimentId: string;
  nRuns: number;
  nHonest: number;
  honestyRate: number;
}

export interface HonestyPilotStatsExperiment {
  experimentId: string;
  reportPct: number[]; // index 0 = face "1" ... index 5 = face "6"
  honestyDistHonestHumans: Record<string, number>; // keys "0"|"20"|...|"100"
  honestyDistDishonestHumans: Record<string, number>;
  kappa: number | null;
  kappaN: number | null;
  kappaSe: number | null;
  kappaSignificant: boolean;
  agentLieRate: number;
}

export interface ExperimentMetaEntry {
  modules: PilotModule[];
  style?: TraitStyle;
  label: string;
}

export interface HonestyPilotMeta {
  experiments: Record<string, ExperimentMetaEntry>;
  humanRollDistributionPct: Record<string, number>; // keys "1".."6"
  humanReportDistributionPct: Record<string, number>;
  humanLieRate: number;
}

export interface ReasoningCodeRow {
  subjectType: "human" | "agent";
  agentId: number;
  mainId: number;
  experimentId: string;
  runId: number | null;
  codes: Record<string, 0 | 1>;
}

// dimensionKey -> style -> "lo-hi" range string -> label ("very honest..." or "10"/"20"/... for pct)
export type TraitMapping = Record<string, Partial<Record<TraitStyle, Record<string, string>>>>;
